### ISSUE TITLE
Compile task fails with Following

### ISSUE THREAD

**Issue by shubhq2** [cooperka/react-native-snackbar#127]
### Task :react-native-snackbar:processDebugManifest FAILED

**Full Log Here:** 

**react-native run-android**

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-fs (to unlink run: "react-native unlink react-native-fs")
  - react-native-snackbar (to unlink run: "react-native unlink react-native-snackbar")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1443 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

> Task :react-native-fs:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-reanimated:compileDebugJavaWithJavac

**> Task :react-native-snackbar:generateDebugBuildConfig FAILED**

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
40 actionable tasks: 27 executed, 13 up-to-date
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-fs\android\src\main\java\com\rnfs\RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-snackbar:generateDebugBuildConfig'.
> java.io.IOException: Unable to delete directory C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-snackbar\android\build\generated\source\buildConfig\debug\com\azendoo.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-fs\android\src\main\java\com\rnfs\RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-snackbar:generateDebugBuildConfig'.
> java.io.IOException: Unable to delete directory C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\react-native-snackbar\android\build\generated\source\buildConfig\debug\com\azendoo.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)
    at buildAndRun (C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (C:\Users\8CG8272KN7\NativeDev\CustomerDashboardApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by cooperka** [comment]
Have you tried the suggested advice:

```
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

Closing for now, please feel free to answer with more details and I'm happy to re-open.
