### ISSUE TITLE
Android: Fatal Exception

### ISSUE THREAD

**Issue by chocky335** [cooperka/react-native-snackbar#93]
It only happens on ANDROID 8

Crashlytics log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
       at android.support.design.widget.Snackbar.make(Snackbar.java:136)
       at com.azendoo.reactnativesnackbar.SnackbarModule.displaySnackbar(SnackbarModule.java:91)
       at com.azendoo.reactnativesnackbar.SnackbarModule.show(SnackbarModule.java:67)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

can't reproduce by myself but it time-to-time happens with our users...

**Comment by cooperka** [comment]
Closed by https://github.com/cooperka/react-native-snackbar/pull/94
