### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by rutvikwebmobtech** [cooperka/react-native-snackbar#97]
My app has a 100K+ users and I got 168 crashes in crashlytics that affected 128 users of my app

`Fatal Exception: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
       at android.support.design.widget.Snackbar.make(Snackbar.java:137)
       at com.azendoo.reactnativesnackbar.SnackbarModule.displaySnackbar(SnackbarModule.java:91)
       at com.azendoo.reactnativesnackbar.SnackbarModule.show(SnackbarModule.java:67)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by cooperka** [comment]
Hmm, are you able to reproduce this? Can you include the version number of this library that you're using?

I'd welcome a PR if you'd like to submit one. Thanks @rutvikwebmobtech.

**Comment by rutvikwebmobtech** [comment]
@cooperka No at the time of development I don't face any issue but I got it from Crashlytics. I am using version 0.4.4

**Comment by cooperka** [comment]
There have been a lot of changes since then, can you try upgrading to [v0.5.3](https://github.com/cooperka/react-native-snackbar/releases/tag/v0.5.3)?

**Comment by rutvikwebmobtech** [comment]
Yes In my latest project I am already using v0.5.3, but the same issue in new project too

**Comment by cooperka** [comment]
Is the line number of the error in 0.5.3 different than the one you originally posted? That would probably be the place to start if anyone wants to tackle this bug.

**Comment by rutvikwebmobtech** [comment]
@cooperka here is the crash log from latest version 

```
Fatal Exception: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
       at android.support.design.widget.Snackbar.make(Snackbar.java:137)
       at com.azendoo.reactnativesnackbar.SnackbarModule.displaySnackbar(SnackbarModule.java:93)
       at com.azendoo.reactnativesnackbar.SnackbarModule.show(SnackbarModule.java:69)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:163)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:760)
```

**Comment by cooperka** [comment]
Excellent. In that case it looks like the fix should be made [here](https://github.com/cooperka/react-native-snackbar/blob/master@%7B2018-12-06%7D/android/src/main/java/com/azendoo/reactnativesnackbar/SnackbarModule.java#L93). Would you like to take a go at it?

**Comment by AntoineAA** [comment]
Hi,
is it fixed?

**Comment by cooperka** [comment]
Hi @AntoineAA, as far as I know nobody has submitted a fix yet. Would you like to tackle it?

**Comment by slavikdenis** [comment]
Just run into this error on release version. If anyone has some idea how to reproduce it, let me know, maybe would try to fix it. Thanks

stack:

```
Fatal Exception: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
       at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:181)
       at com.azendoo.reactnativesnackbar.SnackbarModule.displaySnackbar(SnackbarModule.java:93)
       at com.azendoo.reactnativesnackbar.SnackbarModule.show(SnackbarModule.java:69)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:203)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by nagasaicharan** [comment]
Is there any update on this bug

**Comment by cooperka** [comment]
Hi @nagasaicharan, #144 attempts to resolve this bug but is in need of improvement. Feel free to submit a PR to address the feedback!
